# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

after_success:
  - npm run travis-update

env:
  global:

    # DOC_SEARCH_ID & DOC_SEARCH_KEY
    - secure: "a32kLi5vOMUWcco/4br0JFsd5jD77YK00obaZjQW/ZZtqjDKgZ0uyLWTiBkmQKzbaHCByBf63Q7RzfKQvzZZE5dNdRA5AV6p+XZhKvUtCWSGZl1eNbDh4zuPo+XBg6M1QURBvlRHPaj0/KxkqDCISAt9O5tBkcRPLZBMuvDsDb/+OkUrdxGaLJpxcBPYazhKLCIBaMqat05omb2DkIgBZ9VDPA40wTj2Gbh/M2qgsTEGmo0TxU1BAebBkODOAgvOOf0NlqpOay3Ssl2k7nLNwu5w+2Dyan/U81CMBAcdgrrvGpTrlNKutFIetr3DFl/rjkBrJH8h647L3w7wMclvowSJvEUBW52hxF0BnuUdwLJZUm9LXXZAt9IA+QCZ5kuei0YWPC5ZRNJmZfT+LP98xcsyRFh6gR6138Dn63pW3VVbGt3zmUwkYx3W7BRppsy7kQodntVSxS+wgr0Yqa73dukYtKtxcVXoPcDiUijHMLi+WnU3xMgYR2r50fVKuaaKJfh6vI5tq3FPyVeRxDoCzv6/n90Wjve2tg0574a+OQf5advgNwanX4rXR8VTt57V7Tt1rHkZh5Zagvyc7k5VATDV7NoQTm6R20pbo4mfnAfyFFNStpHpGuDN8T/53IQnpvmjJNofhC2R0ZaFA5ApDb7ZC7Gh/d5/Ze8HQjsqpAk="

    # GH_USER_EMAIL & GH_USER_NAME
    - secure: "eFYQUR5b7vA7Q/kLiabHG5Qldy024n3ARdcEY+vVWMOWi1dAbxFj9/gv0qIxkxzsSdr6yUmG6gjfusows3BbJP56SttFambN5WQcv1gK3m/urtC2v1fFMkKAAd1eDgEkEQXZRN8TeqXpu1RPyYctUiSm6JZ82ah0vNxPXJ9+E3nMv76Ok/tJ2DOO7BUMb4GXGxa0G9lta/M5LHiHMB9IP5vePEO02IrbAzXYgBrLlUp5LwPpugLvijR1gYo+NQvgUy2Zyo5t9YhNAQPfps/C3OfyRHvIc2+hZE12xtBE1M1iTOFBuCKmT9BInbq6tTbjJLOIyaFgfV2So/H0yiegilyFfazqeRN3sVCanUiG7jB2cPQlLvxwjRZvuWXD5uhSwiImzMSmzEEfLDydBj5ZQf941scH1h0s716DHV0G6wsQvu2LZeWrGsz+Mn5ApYKCnd9Ifa9K2mQ5k4JkUzh850PIjzwQE2THYW4uhHcdXgwpoWlQjIqbXue0paYxbgGaXS0IwLNw3sUfh3hIRQmxuPFxvwzD4+NkmxhjvUpAxgPD0t8tvrhhgpPeZ+c5IXKRdOA0jdtzSR9JB1l2CigmTu9gIeTqImGLNaA8pmfvUK0VS5r5jRcsFVDttZ1B745lC2t1vt9LlMJa5xUFehF6bzi9MS6VNo4+aOcc32vkKSc="

language: node_js

dist: trusty

node_js:
  - node

notifications:
  email:
    on_failure: always
    on_success: never
